<?xml version="1.0" encoding="UTF-8"?><testrun name="TestAddressDao.testAdd" project="shop" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="testAdd" classname="info.test.TestAddressDao" time="2.513">
    <error>org.apache.ibatis.exceptions.PersistenceException: &#13;
### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.&#13;
### The error may exist in info/model/User.xml&#13;
### The error may involve info.model.User.load&#13;
### The error occurred while executing a query&#13;
### Cause: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.&#13;
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:95)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:59)&#13;
	at info.dao.BaseDao.load(BaseDao.java:63)&#13;
	at info.dao.UserDao.load(UserDao.java:39)&#13;
	at info.dao.AddressDao.add(AddressDao.java:20)&#13;
	at info.test.TestAddressDao.testAdd(TestAddressDao.java:27)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)&#13;
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1121)&#13;
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:358)&#13;
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2489)&#13;
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2526)&#13;
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2311)&#13;
	at com.mysql.jdbc.ConnectionImpl.&lt;init&gt;(ConnectionImpl.java:834)&#13;
	at com.mysql.jdbc.JDBC4Connection.&lt;init&gt;(JDBC4Connection.java:47)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)&#13;
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)&#13;
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)&#13;
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:416)&#13;
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:347)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:664)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:208)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:181)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.doGetConnection(UnpooledDataSource.java:176)&#13;
	at org.apache.ibatis.datasource.unpooled.UnpooledDataSource.getConnection(UnpooledDataSource.java:80)&#13;
	at org.apache.ibatis.datasource.pooled.PooledDataSource.popConnection(PooledDataSource.java:371)&#13;
	at org.apache.ibatis.datasource.pooled.PooledDataSource.getConnection(PooledDataSource.java:80)&#13;
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:131)&#13;
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:58)&#13;
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:279)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:69)&#13;
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:56)&#13;
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)&#13;
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:141)&#13;
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105)&#13;
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)&#13;
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:101)&#13;
	... 29 more&#13;
Caused by: java.net.ConnectException: Connection refused: connect&#13;
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)&#13;
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)&#13;
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)&#13;
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)&#13;
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)&#13;
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)&#13;
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)&#13;
	at java.net.Socket.connect(Socket.java:589)&#13;
	at java.net.Socket.connect(Socket.java:538)&#13;
	at java.net.Socket.&lt;init&gt;(Socket.java:434)&#13;
	at java.net.Socket.&lt;init&gt;(Socket.java:244)&#13;
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:259)&#13;
	at com.mysql.jdbc.MysqlIO.&lt;init&gt;(MysqlIO.java:308)&#13;
	... 58 more&#13;
&#13;
</error>
  </testcase>
</testrun>
